language: cpp
compiler: gcc

before-install: 
  - sudo apt-get update

install: 
  - sudo apt-get install libev-dev libgoogle-perftools-dev libhiredis-dev libicu-dev libcurl4-openssl-dev libboost-dev libluajit-5.1-dev
  
    
  # Make fserv use the system-provided LuaJIT headers. (This is dirty...)
  - cd ~/build
  - lua_src=f-list/fserv/lib/lua/src
  - mkdir -p $lua_src
  - cp /usr/include/luajit-2.0/* $lua_src
  - cp /usr/lib/x86_64-linux-gnu/libluajit-5.1.a $lua_src/libluajit.a
  - cp /usr/lib/x86_64-linux-gnu/libluajit-5.1.so $lua_src/libluajit.so
  
  # Get libjansson version 2.5, the one in Ubuntu 12.04's repos is way outdated.
  - cd ~/build
  - wget http://www.digip.org/jansson/releases/jansson-2.5.tar.gz
  - tar xvzf jansson-2.5.tar.gz
  - cd jansson-2.5
  - ./configure --prefix=/usr/ && make && sudo make install
  
  # We need to get and build libglog because Ubuntu 12.04 doesn't have that in its repos.
  - cd ~/build
  - wget https://google-glog.googlecode.com/files/glog-0.3.3.tar.gz
  - tar xvzf glog-0.3.3.tar.gz
  - cd glog-0.3.3
  - ./configure && make && sudo make install
  
script: 
  # Finally, build fserv.
  - cd ~/build/f-list/fserv
  - make all
